name: Build EXE and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build EXE
      run: pyinstaller --onefile --distpath . --workpath . --clean --noupx --noconsole store_translator.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: translator
        path: store_translator.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: translator

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: store_translator.exe
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
